
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ghaith al Zein and Hussam Kanaan
 */
public class Manage_Students extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Students
     */
    Students st = new Students();

    public Manage_Students() {
        initComponents();
        this.setLocation(300, 25);
        this.setSize(550, 500);
        this.setTitle("Manage_Students");
    }

    public Manage_Students(Students st) {
        initComponents();
        this.st = st;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        student_id_to_be_deleted = new javax.swing.JTextField();
        deleteStudent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id_to_be_showed_information = new javax.swing.JTextField();
        showStudent = new javax.swing.JButton();
        view_number_of_all_students = new javax.swing.JButton();
        numberOfStudents = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        showAge = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        student_age = new javax.swing.JLabel();
        idForAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 15, 14);

        student_id_to_be_deleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_id_to_be_deletedActionPerformed(evt);
            }
        });
        getContentPane().add(student_id_to_be_deleted);
        student_id_to_be_deleted.setBounds(90, 160, 212, 41);

        deleteStudent.setText("Delete");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        getContentPane().add(deleteStudent);
        deleteStudent.setBounds(330, 160, 150, 40);

        jLabel2.setText(" ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 220, 18, 28);

        id_to_be_showed_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_to_be_showed_informationActionPerformed(evt);
            }
        });
        getContentPane().add(id_to_be_showed_information);
        id_to_be_showed_information.setBounds(90, 220, 212, 40);

        showStudent.setText("Show");
        showStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentActionPerformed(evt);
            }
        });
        getContentPane().add(showStudent);
        showStudent.setBounds(330, 220, 150, 40);

        view_number_of_all_students.setText("View the number of all Students");
        view_number_of_all_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_number_of_all_studentsActionPerformed(evt);
            }
        });
        getContentPane().add(view_number_of_all_students);
        view_number_of_all_students.setBounds(70, 360, 240, 40);

        numberOfStudents.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(numberOfStudents);
        numberOfStudents.setBounds(70, 410, 157, 50);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(330, 360, 150, 40);

        showAge.setText(" Age");
        showAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAgeActionPerformed(evt);
            }
        });
        getContentPane().add(showAge);
        showAge.setBounds(330, 290, 150, 40);

        jLabel3.setText(" ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 270, 18, 37);
        getContentPane().add(student_age);
        student_age.setBounds(270, 420, 230, 40);
        getContentPane().add(idForAge);
        idForAge.setBounds(90, 280, 212, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liu.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 0, 350, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_id_to_be_deletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_id_to_be_deletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_id_to_be_deletedActionPerformed

    private void id_to_be_showed_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_to_be_showed_informationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_to_be_showed_informationActionPerformed

    private void showStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentActionPerformed
        // TODO add your handling code here:
        st.show_Student(id_to_be_showed_information.getText());
    }//GEN-LAST:event_showStudentActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        starting_page sp = new starting_page();
        sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student", "Deleting Student", WIDTH);
        st.deleteStudent(student_id_to_be_deleted.getText(), st);

    }//GEN-LAST:event_deleteStudentActionPerformed

    private void view_number_of_all_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_number_of_all_studentsActionPerformed
        // TODO add your handling code here:
        numberOfStudents.setText(st.get_Nb() + "");
    }//GEN-LAST:event_view_number_of_all_studentsActionPerformed

    private void showAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAgeActionPerformed
        // TODO add your handling code here:
        Age a = st.show_Age(idForAge.getText());
        student_age.setText(a.toString());
    }//GEN-LAST:event_showAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JTextField idForAge;
    private javax.swing.JTextField id_to_be_showed_information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel numberOfStudents;
    private javax.swing.JButton showAge;
    private javax.swing.JButton showStudent;
    private javax.swing.JLabel student_age;
    private javax.swing.JTextField student_id_to_be_deleted;
    private javax.swing.JButton view_number_of_all_students;
    // End of variables declaration//GEN-END:variables
}
