
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ghaith al Zein and Hussam Kanaan
 */
public class manage_employees extends javax.swing.JFrame {

    /**
     * Creates new form manage_employees
     */
    Employees e = new Employees();

    public manage_employees() {
        initComponents();
        this.setLocation(300, 25);
        this.setSize(625, 400);
    }

    public manage_employees(Employees e) {
        initComponents();
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        number_button = new javax.swing.JButton();
        employees_numbers = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        employee_id_to_be_deleted = new javax.swing.JTextField();
        view_information_button = new javax.swing.JButton();
        id_to_be_showed_information = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idAge = new javax.swing.JTextField();
        getAge = new javax.swing.JButton();
        age = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employees Information System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 30, 301, 28);

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button);
        back_button.setBounds(370, 220, 230, 40);

        number_button.setText("View the number of all employees");
        number_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(number_button);
        number_button.setBounds(57, 220, 260, 41);

        employees_numbers.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        employees_numbers.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(employees_numbers);
        employees_numbers.setBounds(150, 280, 190, 47);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 100, 33);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Employee ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 70, 100, 31);

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(delete_button);
        delete_button.setBounds(370, 70, 230, 33);

        employee_id_to_be_deleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_id_to_be_deletedActionPerformed(evt);
            }
        });
        getContentPane().add(employee_id_to_be_deleted);
        employee_id_to_be_deleted.setBounds(150, 70, 190, 31);

        view_information_button.setText("View information");
        view_information_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_information_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(view_information_button);
        view_information_button.setBounds(370, 110, 230, 33);
        getContentPane().add(id_to_be_showed_information);
        id_to_be_showed_information.setBounds(150, 120, 190, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 100, 35);
        getContentPane().add(idAge);
        idAge.setBounds(150, 160, 190, 30);

        getAge.setText("View Age");
        getAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAgeActionPerformed(evt);
            }
        });
        getContentPane().add(getAge);
        getAge.setBounds(370, 170, 230, 35);

        age.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(age);
        age.setBounds(380, 270, 250, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 630, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        starting_page sp = new starting_page();
        sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Delete Student", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            e.deleteEmployee(employee_id_to_be_deleted.getText(), e);
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void employee_id_to_be_deletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_id_to_be_deletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_id_to_be_deletedActionPerformed

    private void view_information_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_information_buttonActionPerformed
        // TODO add your handling code here:
        e.show_Employee(id_to_be_showed_information.getText());
    }//GEN-LAST:event_view_information_buttonActionPerformed

    private void number_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_buttonActionPerformed
        // TODO add your handling code here:
        int i = e.get_Nb();
        employees_numbers.setText(i + "");
    }//GEN-LAST:event_number_buttonActionPerformed

    private void getAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAgeActionPerformed
        // TODO add your handling code here:
        Age a = e.show_Age(idAge.getText());
        age.setText(a.toString());
    }//GEN-LAST:event_getAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JButton back_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField employee_id_to_be_deleted;
    private javax.swing.JLabel employees_numbers;
    private javax.swing.JButton getAge;
    private javax.swing.JTextField idAge;
    private javax.swing.JTextField id_to_be_showed_information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton number_button;
    private javax.swing.JButton view_information_button;
    // End of variables declaration//GEN-END:variables
}
