/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ghaith al Zein and Hussam Kanaan
 */
public class starting_page extends javax.swing.JFrame {

    /**
     * Creates new form starting_page
     */
    public starting_page() {
        initComponents();
        this.setSize(700, 500);
        this.setTitle("Starting Page");
        this.setLocation(200, 75);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add_employees_button = new javax.swing.JButton();
        add_students_button = new javax.swing.JButton();
        manage_employees_button = new javax.swing.JButton();
        manage_students_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Lebanese International University");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 494, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Management Information System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 120, 322, 28);

        add_employees_button.setBackground(new java.awt.Color(204, 204, 255));
        add_employees_button.setText("Add_Employee");
        add_employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employees_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_employees_button);
        add_employees_button.setBounds(130, 160, 200, 50);

        add_students_button.setText("Add_Student");
        add_students_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_students_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_students_button);
        add_students_button.setBounds(370, 160, 200, 50);

        manage_employees_button.setText("Manage_Employees");
        manage_employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_employees_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(manage_employees_button);
        manage_employees_button.setBounds(130, 230, 200, 50);

        manage_students_button.setText("Manage_Students");
        manage_students_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_students_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(manage_students_button);
        manage_students_button.setBounds(370, 230, 200, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/214.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employees_buttonActionPerformed
        employees_insertion ei = new employees_insertion();
        ei.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_employees_buttonActionPerformed

    private void add_students_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_students_buttonActionPerformed
        students_insertion si = new students_insertion();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_students_buttonActionPerformed

    private void manage_employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_employees_buttonActionPerformed
        // TODO add your handling code here:
        manage_employees me = new manage_employees();
        me.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_manage_employees_buttonActionPerformed

    private void manage_students_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_students_buttonActionPerformed
        // TODO add your handling code here:
        Manage_Students ms = new Manage_Students();
        ms.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_manage_students_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(starting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(starting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(starting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(starting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new starting_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employees_button;
    private javax.swing.JButton add_students_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manage_employees_button;
    private javax.swing.JButton manage_students_button;
    // End of variables declaration//GEN-END:variables
}
