
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ghaith al Zein and Hussam Kanaan
 */
public class students_insertion extends javax.swing.JFrame {

    Students st = new Students();

    /**
     * Creates new form students_insertion
     */
    public students_insertion() {
        initComponents();
        this.setSize(600, 675);
        this.setLocation(150, 25);
        this.setTitle("Students_Insertion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        student_first_name = new javax.swing.JTextField();
        student_last_name = new javax.swing.JTextField();
        student_id = new javax.swing.JTextField();
        student_major = new javax.swing.JTextField();
        student_gpa = new javax.swing.JTextField();
        student_completed_credits = new javax.swing.JTextField();
        student_phone = new javax.swing.JTextField();
        student_birth = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        student_address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liu3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(123, 11, 451, 95);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 128, 107, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 181, 107, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 234, 107, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Major :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 275, 107, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phone :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 426, 107, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("GPA :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 320, 107, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("C.Credits :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 373, 107, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Date of Birth:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 479, 107, 22);
        getContentPane().add(student_first_name);
        student_first_name.setBounds(123, 124, 451, 35);
        getContentPane().add(student_last_name);
        student_last_name.setBounds(123, 177, 451, 35);
        getContentPane().add(student_id);
        student_id.setBounds(123, 230, 451, 35);
        getContentPane().add(student_major);
        student_major.setBounds(123, 271, 451, 35);
        getContentPane().add(student_gpa);
        student_gpa.setBounds(123, 316, 451, 35);

        student_completed_credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_completed_creditsActionPerformed(evt);
            }
        });
        getContentPane().add(student_completed_credits);
        student_completed_credits.setBounds(123, 369, 451, 35);
        getContentPane().add(student_phone);
        student_phone.setBounds(123, 422, 451, 35);
        getContentPane().add(student_birth);
        student_birth.setBounds(123, 475, 451, 35);

        save.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(123, 590, 125, 40);

        back.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(450, 590, 124, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Address :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 531, 107, 28);
        getContentPane().add(student_address);
        student_address.setBounds(123, 528, 451, 39);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(82, 42, 0, 37);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/61440.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 2, 590, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_completed_creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_completed_creditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_completed_creditsActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        starting_page sp = new starting_page();
        sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        FileReader st_file;
        String s;
        String[] arr;
        boolean checkBirth = false;
        try {
            st_file = new FileReader("Students.txt");
            BufferedReader br = new BufferedReader(st_file);

            while ((s = br.readLine()) != null) {
                arr = s.split(" ");
                Student student = new Student(arr[0], arr[1], arr[2], arr[3], (int) Integer.parseInt(arr[4]), arr[5], arr[6], Double.parseDouble(arr[7]), (int) Integer.parseInt(arr[8]));
                st.add_old_student(student);
            }
            br.close();
        } catch (IOException e) {

            JOptionPane.showMessageDialog(null, "has not been found", "Wrong User", JOptionPane.WARNING_MESSAGE);
        }

        //the above code is to return the old array of Employees.
        boolean characters_in_id = false;
        if (student_first_name.getText().isEmpty() || student_last_name.getText().isEmpty() || student_id.getText().isEmpty() || student_birth.getText().isEmpty() || student_address.getText().isEmpty() || student_phone.getText().isEmpty() || student_major.getText().isEmpty() || student_gpa.getText().isEmpty() || student_completed_credits.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all required information", "Missed Information", JOptionPane.WARNING_MESSAGE);

        } else {
            for (int i = 0; i < student_id.getText().length(); i++) {
                if (Character.isLetter(student_id.getText().charAt(i))) {
                    characters_in_id = true;
                    JOptionPane.showMessageDialog(this, "Please enter numbers only in the ID field", "Invalid ID", JOptionPane.WARNING_MESSAGE);
                    break;

                }
            }
            if (characters_in_id == false) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyy");
                try {
                    Date birthDate = sdf.parse(student_birth.getText());
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Please enter the date of birth in this form(dd/mm/yyy)", "Invalid Date Of Birth", JOptionPane.WARNING_MESSAGE);
                    checkBirth = true;
                }

                if (!checkBirth) {
                    if (st.check_ID(student_id.getText())) {
                        Student student = new Student(student_first_name.getText(), student_last_name.getText(), student_birth.getText(), student_address.getText(), (int) Integer.parseInt(student_phone.getText()), student_id.getText(), student_major.getText(), Double.parseDouble(student_gpa.getText()), (int) Integer.parseInt(student_completed_credits.getText()));
                        st.addStudent(student);

                    } else {
                        JOptionPane.showMessageDialog(this, "You can not insert two students with the same ID", "Invalid ID", JOptionPane.ERROR_MESSAGE);
                    }
                }

            }
        }
        Manage_Students ms = new Manage_Students(st);
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(students_insertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(students_insertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(students_insertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(students_insertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new students_insertion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton save;
    private javax.swing.JTextField student_address;
    private javax.swing.JTextField student_birth;
    private javax.swing.JTextField student_completed_credits;
    private javax.swing.JTextField student_first_name;
    private javax.swing.JTextField student_gpa;
    private javax.swing.JTextField student_id;
    private javax.swing.JTextField student_last_name;
    private javax.swing.JTextField student_major;
    private javax.swing.JTextField student_phone;
    // End of variables declaration//GEN-END:variables
}
